:PROPERTIES:
:ID: org-smart-enter.el
:END:

#+TITLE: ✨ org-smart-enter.el

#+html: <div align='center'>
#+html: <span class='badge-buymeacoffee'>
#+html: <a href='https://www.paypal.me/darkawower' title='Paypal' target='_blank'><img src='https://img.shields.io/badge/paypal-donate-blue.svg' alt='Buy Me A Coffee donate button' /></a>
#+html: </span>
#+html: <span class='badge-patreon'>
#+html: <a href='https://patreon.com/artawower' target='_blank' title='Donate to this project using Patreon'><img src='https://img.shields.io/badge/patreon-donate-orange.svg' alt='Patreon donate button' /></a>
#+html: </span>
#+html: <a href='https://wakatime.com/badge/github/Artawower/org-smart-enter.el'><img src='https://wakatime.com/badge/github/Artawower/org-smart-enter.el.svg' alt='wakatime'></a>
#+html: </div>

* Introduction
Smart `RET` key for Org-mode buffers: if the cursor is on an Org link, pressing
`RET` opens it; otherwise it falls back to the usual `org-return`.  
Integrates with Evil and Meow modal editors to only override `RET` in normal
state.

This is an *AI-generated* Emacs package, created with the assistance of a large
language model (OpenAI GPT-5).  The core idea and requirements were provided
by the author, while the implementation and documentation were generated and
refined through iterative collaboration with the AI.

* Connected links
- [[https://orgmode.org][Org Mode Documentation]]
- [[https://github.com/meow-edit/meow][Meow modal editing]]
- [[https://github.com/emacs-evil/evil][Evil mode]]

* Install
This package requires **Emacs 27.1** or later and **Org 9.4** or later.

** quelpa
You can fetch the package directly from GitHub using [[https://github.com/quelpa/quelpa][quelpa]]:

#+BEGIN_SRC emacs-lisp
(use-package org-smart-enter
  :quelpa (org-smart-enter :fetcher github :repo "artawower/org-smart-enter.el")
  :hook (org-mode . org-smart-enter-mode))
#+END_SRC

** straight.el
With [[https://github.com/radian-software/straight.el][straight.el]] you can specify a recipe:

#+BEGIN_SRC emacs-lisp
(use-package org-smart-enter
  :straight (org-smart-enter :type git :host github :repo "artawower/org-smart-enter.el")
  :hook (org-mode . org-smart-enter-mode))
#+END_SRC

** Doom Emacs
For [[https://github.com/hlissner/doom-emacs][Doom Emacs]] add the package to your `~/.doom.d/packages.el`:

#+BEGIN_SRC emacs-lisp
(package! org-smart-enter :recipe (:host github :repo "artawower/org-smart-enter.el"))
#+END_SRC

Then enable it in your `~/.doom.d/config.el`:

#+BEGIN_SRC emacs-lisp
(use-package! org-smart-enter
  :hook (org-mode . org-smart-enter-mode))
#+END_SRC

* Usage
To use the package, require it and enable the minor mode in your Org buffers:

#+BEGIN_SRC emacs-lisp
(require 'org-smart-enter)
(add-hook 'org-mode-hook #'org-smart-enter-mode)
#+END_SRC

When `org-smart-enter-mode` is active:
- Pressing `RET` over an Org link follows the link.
- Otherwise it inserts a newline.
- If Evil is loaded, the binding applies only in normal state.
- If Meow is loaded, it remaps `RET` in `meow-normal-state-keymap`.
- In insert state or without modal editors, `RET` works normally.

* 🍩 Contribute guide
Any contribution is very much appreciated!  
Please read the [[./CONTRIBUTE.org][style guide]] before contributing to avoid misunderstandings!  
I would also appreciate it if you would consider becoming my [[https://www.patreon.com/artawower][patron]].  

Contributions can include:
- Bug reports
- Feature requests
- Documentation improvements
- Code patches

This project is licensed under the GNU General Public License version 3 or later, so please ensure your contributions are compatible with that license.
